# PROBLEM 1
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23
# Find the sum of all the multiples of 3 or 5 below 1000.

sum = 0 # create variable for the sum of all of the numbers
for integer in range(1000): # for loop which will cycle through every number UNDER 1000
    if (integer%3 == 0 or integer%5 == 0): # if number is divisible by 3 or 5
        sum += integer # add number to total sum
print(sum)

# COMPLETE : 233168


# PROBLEM 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

evens_sum = 2 # set even sum to the already existing sum for evens just 2
number_list = [1,2] # create a list of numbers, starting with the two already existing
term_limit = True # declare term limit as true
while term_limit: 
        term = number_list[-1] + number_list[-2] # add together the last two values in the number_list
        if term <= 4000000: # if the term is less than or equal to the set value (4,000,000)
            if term%2 == 0: # if the term is even
                evens_sum += term # add the term to the sum of evens
            number_list.append(term) # append the term to the end of number_list
        else:
                term_limit = False # set term_limit to false once term limit is reached (stops while loop)
print('evens total: ', evens_sum)

# COMPLETE : 4613732


# PROBLEM 3
# The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?

from primePy import primes # using primePy library might try to get another solution to work without it

last_num = 1
gatekeeper = 0
def recursive_prime_factoring(the_number):
    global last_num
    global gatekeeper
    for integer in range(last_num + 1, int(the_number + 1)):
            if gatekeeper == 0:
                for i in range(2, int(integer/2)+1):
                    if gatekeeper == 0: 
                        if (integer % i) == 0:
                                break
                    else:
                         break
                else:
                    last_num = integer
                    if the_number%integer == 0:
                        the_number = the_number/integer
                        static_num = the_number*integer 
                        if gatekeeper == 0: 
                            if primes.check(the_number):
                                if the_number == 1:
                                    print(static_num, "is its own highest prime factor")
                                    gatekeeper=1
                                    break   
                                else:
                                    print(the_number, "is the highest prime factor")
                                    gatekeeper=1
                                    break   
                            else:
                                last_num = 1
                                recursive_prime_factoring(the_number)
                        else:
                            break    
                    else:
                        recursive_prime_factoring(the_number)
recursive_prime_factoring(600851475143)

# a much simpler solution using primePy

from primePy import primes

high_prime_factor = max(primes.factors(600851475143))
print(high_prime_factor)

# COMPLETE : 6857


# PROBLEM 4
#  A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 times 99. Find the largest palindrome made from the product of two 3-digit numbers.

num3 = 0
num3_dict=[]
p_list=[]
gate = False
force = 1
power = 0
for num1 in range(100,1000):
    for num2 in range(100,1000):
            num3 = num1*num2
            num3_string = str(num3)
            for i in num3_string:
                    num3_dict.append(i)
            if len(num3_dict) == 6:
                if num3_dict[0] == num3_dict[-1] and num3_dict[1] == num3_dict[-2] and num3_dict[2] == num3_dict[-3]:
                    p_list.append(num3)
                else:
                    num3_dict.clear()
            else:
                    if num3_dict[0] == num3_dict[-1] and num3_dict[1] == num3_dict[-2]:
                        p_list.append(num3)
                    else:
                        num3_dict.clear()
last_p = 0
for p in p_list:
     if p > last_p:
          last_p = p
print("Largest palindrome:",last_p)

# COMPLETE : 906609


# PROBLEM 5
# 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
# What is the smallest positive number that is evenly divisible with no remainder by all of the numbers from 1 to 20?

num1 = 0
num2 = 2520 # any number divisible by 1 - 20 must be divisible by 2520
while num1 != 20:
    num1 = 0
    num2 += 2520
    for i in range(1,21):
        if num2 % i == 0:
            num1 += 1
print(num2)

# COMPLETE : 232792560

# PROBLEM 6
# Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

sum = 0
sum1 = 0
def square(x):
     return x*x
for number in range(1,101):
     sum1 += number
     math = square(number)
     sum += math
sum1 = square(sum1)
diff = sum1 - sum
print(diff)

# COMPLETE : 25164150